# Generated by Django 5.1.7 on 2025-07-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
