# Generated by Django 5.1.7 on 2025-07-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_habitlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=100),
        ),
    ]
